# Generated by Django 5.2.9 on 2026-06-09 20:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la asignatura')),
                ('codigo_asignatura', models.CharField(max_length=50, verbose_name='Código de asignatura')),
                ('codigo_horario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de horario')),
                ('total_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total de horas')),
                ('total_creditos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Total de créditos')),
                ('total_laboratorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total de laboratorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['programa__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la facultad')),
                ('siglas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Siglas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la plantilla')),
                ('tipo_documento', models.CharField(choices=[('nota_docente', 'Nota dirigida al docente'), ('calendario_pago', 'Calendario de pago'), ('reporte', 'Reporte'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='plantillas/', verbose_name='Archivo de plantilla')),
                ('contenido_html', models.TextField(blank=True, help_text='Plantilla HTML editable para generar PDF.', null=True, verbose_name='Contenido HTML')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['tipo_documento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(max_length=50, unique=True, verbose_name='Cédula')),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='organizacion_docente.facultad', verbose_name='Facultad relacionada')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='OrganizacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de pago')),
                ('cedula_docente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula del docente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año académico')),
                ('semestre', models.CharField(choices=[('I', 'I Semestre'), ('II', 'II Semestre'), ('VERANO', 'Verano'), ('ESPECIAL', 'Periodo Especial')], max_length=20, verbose_name='Semestre')),
                ('grupo_aula', models.CharField(max_length=100, verbose_name='Grupo / Aula')),
                ('codigo_asignatura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de asignatura')),
                ('codigo_horario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de horario')),
                ('total_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total de horas')),
                ('fechas_clases', models.TextField(blank=True, help_text='Puede escribir las fechas separadas por coma, rango o descripción.', null=True, verbose_name='Fechas de clases')),
                ('horario', models.TextField(blank=True, null=True, verbose_name='Horario')),
                ('fecha_matricula', models.DateField(blank=True, null=True, verbose_name='Fecha de matrícula')),
                ('cantidad_estudiantes_matriculados', models.PositiveIntegerField(default=0, verbose_name='Cantidad de estudiantes matriculados')),
                ('total_creditos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Total de créditos')),
                ('total_laboratorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total laboratorio')),
                ('total_no_exonerados', models.PositiveIntegerField(default=0, verbose_name='Total no exonerados')),
                ('cantidad_exoneracion_50', models.PositiveIntegerField(default=0, verbose_name='Cantidad de estudiantes con exoneración del 50%')),
                ('cantidad_exoneracion_25', models.PositiveIntegerField(default=0, verbose_name='Cantidad de estudiantes con exoneración del 25%')),
                ('ingreso_laboratorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ingreso por laboratorio B/.')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de ingresos')),
                ('pago_docente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pago del docente B/.')),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Utilidad neta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='organizacion_docente.asignatura', verbose_name='Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='organizacion_docente.docente', verbose_name='Docente')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='organizacion_docente.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Organización Docente',
                'verbose_name_plural': 'Organizaciones Docentes',
                'ordering': ['-anio', 'semestre', 'facultad__nombre', 'programa__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campo', models.CharField(max_length=150, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cambio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_organizacion_docente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='organizacion_docente.organizaciondocente', verbose_name='Organización docente')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaPostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del programa')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del programa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='organizacion_docente.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Programa de Postgrado',
                'verbose_name_plural': 'Programas de Postgrado',
                'ordering': ['facultad__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='organizacion_docente.programapostgrado', verbose_name='Programa de postgrado'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='organizacion_docente.programapostgrado', verbose_name='Programa de postgrado'),
        ),
        migrations.CreateModel(
            name='EstadoProcesoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_estado', models.CharField(choices=[('horario_elaborado', 'Horario elaborado'), ('organizacion_docente_elaborada', 'Organización docente elaborada'), ('calendario_pago_elaborado_enviado', 'Calendario de pago elaborado y enviado'), ('organizacion_enviada_vipe', 'Organización docente enviada a la VIPE'), ('organizacion_con_numero_posicion', 'Organización docente con número de posición'), ('organizacion_enviada_firma_electronica', 'Organización docente enviada para firma electrónica'), ('firmado_por_autoridades', 'Firmado por autoridades'), ('organizacion_enviada_recursos_humanos', 'Organización docente enviada a Recursos Humanos'), ('acta_recibida', 'Acta recibida'), ('acta_firmada_enviada_rh', 'Acta firmada enviada a Recursos Humanos')], max_length=100, verbose_name='Tipo de estado')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('usuario_completo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_completados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que completó')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='organizacion_docente.organizaciondocente', verbose_name='Organización docente')),
            ],
            options={
                'verbose_name': 'Estado del Proceso',
                'verbose_name_plural': 'Estados del Proceso',
                'ordering': ['organizacion', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organizacion', 'tipo_estado'), name='estado_unico_por_organizacion')],
            },
        ),
        migrations.AddConstraint(
            model_name='programapostgrado',
            constraint=models.UniqueConstraint(fields=('facultad', 'nombre'), name='programa_unico_por_facultad'),
        ),
        migrations.AddIndex(
            model_name='organizaciondocente',
            index=models.Index(fields=['anio', 'semestre'], name='organizacio_anio_9d3a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizaciondocente',
            index=models.Index(fields=['numero_pago'], name='organizacio_numero__1958ae_idx'),
        ),
        migrations.AddIndex(
            model_name='organizaciondocente',
            index=models.Index(fields=['cedula_docente'], name='organizacio_cedula__c15561_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('programa', 'codigo_asignatura'), name='codigo_asignatura_unico_por_programa'),
        ),
    ]
