# Generated by Django 5.2.9 on 2026-06-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciondocente',
            name='fecha_matricula_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: 16 y 17 de junio, 2026', max_length=255, verbose_name='Fecha de matrícula texto'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='primer_pago_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Del 17 al 30 de junio de 2026', max_length=255, verbose_name='Primer pago / Primer tercio'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='retiro_fuera_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Del 29 de junio al 24 de julio de 2026', max_length=255, verbose_name='Retiro fuera del periodo'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='retiro_inclusion_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Del 22 al 28 de junio de 2026', max_length=255, verbose_name='Retiro/Inclusión de asignaturas'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='segundo_pago_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Del 1 al 15 de julio de 2026', max_length=255, verbose_name='Segundo pago / Segundo tercio'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='tercer_pago_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Del 16 al 27 de julio de 2026', max_length=255, verbose_name='Tercer pago / Tercer tercio'),
        ),
    ]
