# Generated by Django 5.2.9 on 2026-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0002_organizaciondocente_fecha_matricula_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizaciondocente',
            name='semestre',
            field=models.CharField(choices=[('I', 'I Semestre'), ('II', 'II Semestre'), ('VERANO', 'Verano'), ('ESPECIAL', 'Periodo Especial'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre')], max_length=20, verbose_name='Semestre'),
        ),
    ]
