# Generated by Django 5.2.9 on 2026-06-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0003_alter_organizaciondocente_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohorteProgramaPostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('grupo', models.CharField(blank=True, help_text='Ejemplo: 2AG211, 2MD212, 2MO211', max_length=50, verbose_name='Grupo')),
                ('anio_reporte', models.PositiveIntegerField(help_text='Ejemplo: 2025', verbose_name='Año del reporte')),
                ('estado_informe', models.CharField(choices=[('CONTINUA', 'Programa que continúa'), ('CULMINADO', 'Programa culminado'), ('INICIADO', 'Programa que inició')], default='CONTINUA', max_length=20, verbose_name='Tipo de registro para informe')),
                ('matriculados_inicio', models.PositiveIntegerField(default=0, verbose_name='Matriculados al inicio del programa')),
                ('matriculados_actualmente', models.PositiveIntegerField(default=0, verbose_name='Matriculados actualmente')),
                ('periodo_inicio', models.CharField(blank=True, choices=[('VERANO', 'Verano'), ('I', 'I Semestre'), ('II', 'II Semestre'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre'), ('T1', 'I Trimestre'), ('T2', 'II Trimestre'), ('T3', 'III Trimestre'), ('T4', 'IV Trimestre'), ('ESPECIAL', 'Periodo Especial')], max_length=20, verbose_name='Periodo de inicio')),
                ('periodo_finalizacion', models.CharField(blank=True, choices=[('VERANO', 'Verano'), ('I', 'I Semestre'), ('II', 'II Semestre'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre'), ('T1', 'I Trimestre'), ('T2', 'II Trimestre'), ('T3', 'III Trimestre'), ('T4', 'IV Trimestre'), ('ESPECIAL', 'Periodo Especial')], max_length=20, verbose_name='Periodo de finalización')),
                ('inicio_texto', models.CharField(blank=True, help_text='Ejemplo: II Cuatrimestre 2025 (Mayo - Agosto, 2025)', max_length=255, verbose_name='Inicio texto')),
                ('finaliza_texto', models.CharField(blank=True, help_text='Ejemplo: I Cuatrimestre 2027 (Enero - Abril, 2027)', max_length=255, verbose_name='Finaliza texto')),
                ('observacion', models.CharField(blank=True, help_text='Ejemplo: ACTIVO, CULMINÓ, ACTIVO AL 2026', max_length=255, verbose_name='Observación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='organizacion_docente.programapostgrado', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Cohorte de programa de postgrado',
                'verbose_name_plural': 'Cohortes de programas de postgrado',
                'ordering': ['-anio_reporte', 'programa__facultad__nombre', 'programa__nombre', 'grupo'],
            },
        ),
    ]
