# Generated by Django 5.2.9 on 2026-06-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0004_cohorteprogramapostgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='estado_informe',
            field=models.CharField(choices=[('CONTINUA', 'Programa que continúa'), ('CULMINADO', 'Programa culminado'), ('INICIADO', 'Programa que inició')], default='CONTINUA', help_text='Indica si el programa continuó, culminó o inició en el año del informe.', max_length=20, verbose_name='Tipo de registro para informe'),
        ),
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='finaliza_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Verano, 2027 (Enero - Abril, 2027)', max_length=255, verbose_name='Finaliza texto'),
        ),
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='inicio_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: I Semestre, 2025 (Mayo, 2025)', max_length=255, verbose_name='Inicio texto'),
        ),
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='periodo_finalizacion',
            field=models.CharField(blank=True, choices=[('VERANO', 'Verano'), ('I', 'I Semestre'), ('II', 'II Semestre'), ('T1', 'I Trimestre'), ('T2', 'II Trimestre'), ('T3', 'III Trimestre'), ('T4', 'IV Trimestre'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre'), ('ESPECIAL', 'Periodo Especial')], max_length=20, verbose_name='Periodo de finalización'),
        ),
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='periodo_inicio',
            field=models.CharField(blank=True, choices=[('VERANO', 'Verano'), ('I', 'I Semestre'), ('II', 'II Semestre'), ('T1', 'I Trimestre'), ('T2', 'II Trimestre'), ('T3', 'III Trimestre'), ('T4', 'IV Trimestre'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre'), ('ESPECIAL', 'Periodo Especial')], max_length=20, verbose_name='Periodo de inicio'),
        ),
        migrations.AlterField(
            model_name='cohorteprogramapostgrado',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='organizacion_docente.programapostgrado', verbose_name='Programa de postgrado'),
        ),
    ]
