# Generated by Django 5.2.9 on 2026-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0005_alter_cohorteprogramapostgrado_estado_informe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciondocente',
            name='estado_informe_programa',
            field=models.CharField(blank=True, choices=[('', 'No incluir en informe'), ('CONTINUA', 'Programa que continúa'), ('CULMINADO', 'Programa culminado'), ('INICIADO', 'Programa que inició')], default='', help_text='Indica si el programa continúa, inició o culminó en el año del informe.', max_length=20, verbose_name='Estado del programa en el informe'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='finaliza_texto_programa',
            field=models.CharField(blank=True, help_text='Ejemplo: Verano, 2027 (Enero - Abril, 2027)', max_length=255, verbose_name='Finaliza texto para informe'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='incluir_en_informe_programas',
            field=models.BooleanField(default=False, help_text='Marca esta opción si esta organización debe aparecer en el informe anual de programas.', verbose_name='Incluir en informe de programas'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='inicio_texto_programa',
            field=models.CharField(blank=True, help_text='Ejemplo: I Semestre, 2025 (Mayo, 2025)', max_length=255, verbose_name='Inicio texto para informe'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='matriculados_actuales_programa',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, se puede usar la cantidad de estudiantes matriculados de la organización docente.', null=True, verbose_name='Matriculados actualmente'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='matriculados_inicio_programa',
            field=models.PositiveIntegerField(blank=True, help_text='Ejemplo: cantidad de estudiantes con la que inició el grupo o cohorte.', null=True, verbose_name='Matriculados al inicio del programa'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='observacion_informe_programa',
            field=models.CharField(blank=True, help_text='Ejemplo: ACTIVO, CULMINÓ, ACTIVO AL 2026', max_length=255, verbose_name='Observación para informe'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='periodo_finalizacion_programa',
            field=models.CharField(blank=True, choices=[('I', 'I Semestre'), ('II', 'II Semestre'), ('VERANO', 'Verano'), ('ESPECIAL', 'Periodo Especial'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre')], help_text='Periodo académico estimado o real de finalización del programa.', max_length=20, verbose_name='Periodo de finalización del programa'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='periodo_inicio_programa',
            field=models.CharField(blank=True, choices=[('I', 'I Semestre'), ('II', 'II Semestre'), ('VERANO', 'Verano'), ('ESPECIAL', 'Periodo Especial'), ('C1', 'I Cuatrimestre'), ('C2', 'II Cuatrimestre'), ('C3', 'III Cuatrimestre')], help_text='Periodo académico en que inició el programa o cohorte.', max_length=20, verbose_name='Periodo de inicio del programa'),
        ),
    ]
