# Generated by Django 5.2.9 on 2026-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_docente', '0006_organizaciondocente_estado_informe_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciondocente',
            name='cantidad_posiciones_a_utilizar',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de posiciones que realmente se utilizarán.', verbose_name='Cantidad de posiciones a utilizar'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='cantidad_posiciones_asignadas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad total de posiciones asignadas para esta organización.', verbose_name='Cantidad de posiciones asignadas'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='incluir_en_reporte_posiciones',
            field=models.BooleanField(default=False, help_text='Marca esta opción si esta organización docente debe aparecer en el reporte de posiciones.', verbose_name='Incluir en reporte de posiciones'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='monto_unitario_posicion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, el sistema calcula el monto según el tipo de posición.', max_digits=10, null=True, verbose_name='Monto unitario de la posición'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='observacion_posicion',
            field=models.CharField(blank=True, help_text='Observación opcional para el reporte de posiciones.', max_length=255, verbose_name='Observación de posición'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='origen_posicion',
            field=models.CharField(blank=True, choices=[('SOLICITADA', 'Posición solicitada'), ('REASIGNADA', 'Posición reasignada')], default='SOLICITADA', help_text='Indica si la posición fue solicitada o reasignada.', max_length=20, verbose_name='Origen de la posición'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='posicion_programa_nuevo',
            field=models.BooleanField(default=False, help_text='Marca esta opción si la posición corresponde a un programa nuevo. En el reporte aparecerá con **.', verbose_name='Posición de programa nuevo'),
        ),
        migrations.AddField(
            model_name='organizaciondocente',
            name='tipo_posicion',
            field=models.CharField(blank=True, choices=[('16', 'Posición de 16 horas - B/. 640.00'), ('32', 'Posición de 32 horas - B/. 1,280.00'), ('48', 'Posición de 48 horas - B/. 1,920.00'), ('64', 'Posición de 64 horas - B/. 2,560.00')], help_text='Ejemplo: posición de 16, 32, 48 o 64 horas.', max_length=10, verbose_name='Tipo de posición'),
        ),
    ]
